"""Change habit type enum to ABOVE/BELOW

Revision ID: 22278c8ea914
Revises: d5ebc872aeff
Create Date: 2025-08-21 15:51:04.679129

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '22278c8ea914'
down_revision = 'd5ebc872aeff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.ENUM('BINARY', 'QUANTITATIVE'),
               type_=sa.Enum('ABOVE', 'BELOW', 'BINARY', 'QUANTITATIVE', name='habittype'),
               existing_nullable=False)
        
    batch_op.execute("UPDATE habit SET type='ABOVE'")

    with op.batch_alter_table('habit', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.ENUM('BINARY', 'QUANTITATIVE', 'ABOVE', 'BELOW'),
               type_=sa.Enum('ABOVE', 'BELOW', name='habittype'),
               existing_nullable=False)
        

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('ABOVE', 'BELOW', name='habittype'),
               type_=mysql.ENUM('BINARY', 'QUANTITATIVE', 'ABOVE', 'BELOW'),
               existing_nullable=False)
    batch_op.execute("UPDATE habit SET type='QUANTITATIVE'")
    with op.batch_alter_table('habit', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('ABOVE', 'BELOW', 'BINARY', 'QUANTITATIVE', name='habittype'),
               type_=mysql.ENUM('BINARY', 'QUANTITATIVE'),
               existing_nullable=False)

    # ### end Alembic commands ###
