"""Add cascading deletes to ProgressEntries

Revision ID: 9196b5369c02
Revises: 2db023a8d5c2
Create Date: 2025-04-27 11:40:18.546873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9196b5369c02'
down_revision = '2db023a8d5c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress_entry', schema=None) as batch_op:
        batch_op.drop_constraint('progress_entry_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'habit', ['habit_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress_entry', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('progress_entry_ibfk_1', 'habit', ['habit_id'], ['id'])

    # ### end Alembic commands ###
