"""Add indexes to ProgressEntry for performance

Revision ID: f55a482ec99d
Revises: a94da431b8cc
Create Date: 2026-01-17 12:17:47.210487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f55a482ec99d'
down_revision = 'a94da431b8cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_progress_entry_date'), ['date'], unique=False)
        batch_op.create_index('ix_progress_entry_habit_date', ['habit_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_progress_entry_habit_id'), ['habit_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progress_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_progress_entry_habit_id'))
        batch_op.drop_index('ix_progress_entry_habit_date')
        batch_op.drop_index(batch_op.f('ix_progress_entry_date'))

    # ### end Alembic commands ###
